### ISSUE TITLE
gl-clear ?

### ISSUE THREAD

**Issue by mattdesl** [stackgl/learning-webgl-01#1]
should gl-clear be used instead of raw gl calls? Thoughts?

**Comment by mikolalysenko** [comment]
Seems reasonable.

**Comment by hughsk** [comment]
@mattdesl good point! Updated.

These days I find it easier to just use `gl.clear` directly in my projects, but I initially wrote `gl-clear` because for me it wasn't immediately obvious what was happening. So it's probably worth using it here :)
